# Generated by Django 2.2.16 on 2022-11-21 09:33

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221117_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'администратор'), ('user', 'пользователь'), ('moderator', 'медератор')], default='user', max_length=9, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким username уже существует!'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator], verbose_name='Имя пользователя'),
        ),
    ]
